# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_django_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='user_level',
        ),
    ]
