# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_django_app', '0002_remove_register_user_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poked', models.IntegerField()),
                ('got_poked', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='register',
            name='poked',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poking',
            name='who_poked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_django_app.Register'),
        ),
    ]
