# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_django_app', '0003_auto_20160624_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='dob',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
    ]
