# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_django_app', '0004_register_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='dob',
            field=models.DateTimeField(editable=False),
        ),
    ]
