# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_django_app', '0005_auto_20160624_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='dob',
        ),
    ]
